changelog:
  categories:
    - title: "Breaking Changes"
      labels:
        - breaking
    - title: "New Models"
      labels:
        - model
    - title: "New Views"
      labels:
        - view
    - title: "Field & SQL Changes"
      labels:
        - field-change
        - sql-logic
    - title: "Bug Fixes"
      labels:
        - bugfix
    - title: "Other"
      labels:
        - "*"
