changelog:
  categories:
    - title: "Breaking Changes"
      labels:
        - major-change
    - title: "New Models"
      labels:
        - model
    - title: "New Views"
      labels:
        - view
    - title: "Changes"
      labels:
        - minor-change
        - patch-change
    - title: "Other"
      labels:
        - "*"
