name: Validate Manifest JSON

on:
  pull_request:
    paths:
      - 'manifest.json'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate manifest.json
        uses: vinlee19/manifest-validator-action@v1